import * as RC from "./realCurrencies";
import * as CC from "./cryptoCurrencies";

import { ReactComponent as UpIcon } from "../../icons/up.svg";
import { ReactComponent as DownIcon } from "../../icons/down.svg";

import { ReactComponent as Exchange } from "../../icons/exchange.svg";

export type TIcons = {
  [value: string]: JSX.Element;
};

export const icons: TIcons = {
  BCH: <CC.BCH />,
  BTC: <CC.BTC />,
  DAI: <CC.DAI />,
  USDT: <CC.USDT />,
  EOS: <CC.EOS />,
  ETH: <CC.ETH />,
  QTUM: <CC.QTUM />,
  TRX: <CC.TRX />,
  XRP: <CC.XRP />,
  LTC: <CC.LTC />,
  USDC: <CC.USDC />,
  ADA: <CC.ADA />,
  DOGE: <CC.DOGE />,
  HAI: <CC.HAI />,
  ONE: <CC.ONE />,
  UNI: <CC.UNI />,
  XLM: <CC.XLM />,
  XEM: <CC.XEM />,
  XTZ: <CC.XTZ />,

  ARS: <RC.ARS />,
  AUD: <RC.AUD />,
  AZN: <RC.AZN />,
  BRL: <RC.BRL />,
  GBP: <RC.GBP />,
  BGN: <RC.BGN />,
  CAD: <RC.CAD />,
  CLP: <RC.CLP />,
  COP: <RC.COP />,
  CRC: <RC.CRC />,
  CZK: <RC.CZK />,
  DKK: <RC.DKK />,
  DOP: <RC.DOP />,
  EUR: <RC.EUR />,
  GEL: <RC.GEL />,
  HKD: <RC.HKD />,
  HUF: <RC.HUF />,
  INR: <RC.INR />,
  IDR: <RC.IDR />,
  ILS: <RC.ILS />,
  JPY: <RC.JPY />,
  KZT: <RC.KZT />,
  MYR: <RC.MYR />,
  MXN: <RC.MXN />,
  MDL: <RC.MDL />,
  MAD: <RC.MAD />,
  NAD: <RC.NAD />,
  TWD: <RC.TWD />,
  NZD: <RC.NZD />,
  NGN: <RC.NGN />,
  NOK: <RC.NOK />,
  PEN: <RC.PEN />,
  UYU: <RC.UYU />,
  PHP: <RC.PHP />,
  PLN: <RC.PLN />,
  QAR: <RC.QAR />,
  RON: <RC.RON />,
  RUB: <RC.RUB />,
  SGD: <RC.SGD />,
  ZAR: <RC.ZAR />,
  KRW: <RC.KRW />,
  SEK: <RC.SEK />,
  CHF: <RC.CHF />,
  TRY: <RC.TRY />,
  UAH: <RC.UAH />,
  AED: <RC.AED />,
  USD: <RC.USD />,
  UZS: <RC.UZS />,
  VND: <RC.VND />,

  upArrow: <UpIcon />,
  downArrow: <DownIcon />,
  exchange: <Exchange />,
};
